image: node:latest

stages:
  - build
  - test
  - clean_up

cache:
  paths:
    - node_modules/


run_tests:
  stage: test
  script:
    - npm test

build_and_deploy_prod:
  stage: build
  script:
    - npm install
    - npm run start
    - apt-get install -yqq ruby ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=gst-project --api-key=$HEROKU_API_KEY
  artifacts:
    paths:
      - node_modules/
      - public/static/dist/
  only:
    - depl-struct

clean_up_job:
  stage: clean_up
  script:
    - rm -rf node_modules
    - rm -rf ~/.node-gyp
  when: on_failure
