image: node:argon

before_script:
  - apt-get -qq update
  - apt-get -qq install -y python2.7 python2.7-dev build-essential make gcc g++ libicu-dev
  - npm -g install npm --silent
  - npm set progress=false
  - npm install --silent

stages:
  - build
  - test
  - clean_up

cache:
  paths:
    - node_modules/


run_tests:
  stage: test
  script:
    - npm test

build_and_deploy_prod:
  stage: build
  script:
    - npm run start
    - apt-get install -yqq ruby ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=gst-project --api-key=$HEROKU_API_KEY
  artifacts:
    paths:
      - node_modules/
      - public/static/dist/
  only:
    - depl-struct

clean_up_job:
  stage: clean_up
  script:
    - rm -rf node_modules
    - rm -rf ~/.node-gyp
  when: on_failure
